- name: Install libvirt
  package: name={{item}} state=present
  with_items:
    - qemu-kvm
    - libvirt-bin
    - python-libvirt

- name: Setup libvirt management services
  service: name={{item}} enabled=yes state=started
  with_items:
    - libvirtd
    - libvirt-guests

- name: Add management user to the libvirt group
  user: name={{libvirt_mgmt_user}} groups=libvirtd append=yes

