- name: Install ovs
  package: name={{item}} state=present
  with_items:
    - openvswitch-common
    - openvswitch-switch

- name: Setup ovs management services
  service: name=openvswitch-switch enabled=yes state=started

- name: Setup ovs switches
  openvswitch_bridge: bridge={{item}}
  with_items: ovs_interfaces

