---
- name: Install htop
  package: name=htop state=present

- name: Install vim
  package: name=vim state=present

- name: Install git
  package: name=git state=present

- name: Install Chrony
  apt: pkg=chrony state=installed

- name: Enable chronyd
  service:
    name: chronyd
    state: started
    enabled: yes

- name: Set TimeZone in /etc/localtime
  command: /usr/bin/timedatectl set-timezone Europe/Berlin

- name: Set ntp enabled
  command: /usr/bin/timedatectl set-ntp true
