---
- name: Install htop
  package: name=htop state=present

- name: Install vim
  package: name=vim state=present

- name: Install git
  package: name=git state=present

- name: Install chrony
  package: name=chrony state=present

- name: Enable and start chrony
  service: name=chrony enabled=yes state=started

- name: Set TimeZone in /etc/localtime
  command: /usr/bin/timedatectl set-timezone Europe/Berlin

- name: Set ntp enabled
  command: /usr/bin/timedatectl set-ntp true
