---
- name: Install htop
  package: name=htop state=present

- name: Install vim
  package: name=vim state=present

- name: Install git
  package: name=git state=present

- name: Install ntpd
  package: name=ntp state=present

- name: Ensure the ntpd is started
  service: name=ntp state=started enabled=true
  when: ansible_os_family == "Debian"

- name: Ensure the ntpd is started
  service: name=ntpd state=started enabled=true
  when: ansible_os_family == "Archlinux"

