#raids:
#  - device: /dev/md0
#    level: 1
#    components:
#      - /dev/sdb
#      - /dev/sdc

#lvms:
#  - device: /dev/md0
#    vg_name: boxes

ovs_interfaces:
  - name: br-public
    forward: true
    ip: 91.195.220.65/28
    ip6: 2001:67c:220:12::/64

dhcp:
  - subnet: 91.195.220.64
    netmask: 255.255.255.240
    gateway: 91.195.220.65
    nameservers: 8.8.8.8

libvirt:
#  mgmt_users:
#    - leonard
  storage_pools:
    - name: vg_ssd
      vg_name: vg_ssd
      vg_phy: /dev/md0

# Virtual machines that should exist
# - name should not be changed afterwards
# - memory unit: Gigabytes
# - network interfaces have to be assigned to an ovs_interface switch.
#   Also make sure that the mac address is uniqe and that the ipv4 address has
#   a corresponding dhcp subnet.
# - storage devices have to have a dev-name, e.g. "vda". Make sure not to change
#   this as the storage's identifier is composed of it
boxes:
  - name: noot.techel.net
    memory: 2
    cpus: 4
    install: /ubuntu-14.04/pxelinux.0
    interfaces:
      - switch: br-public
        mac: 00:16:3E:ED:D1:1A
        address: 91.195.220.67
    storage:
      - pool: vg_ssd
        size: 50G
        dev: vda
  - name: irc.reichsinter.net
    memory: 1
    cpus: 1
    install: /archlinux/pxelinux.0
    interfaces:
      - switch: br-public
        mac: 00:16:3E:5A:5C:82
        address: 91.195.220.69
    storage:
      - pool: vg_ssd
        size: 5G
        dev: vda
  - name: tbd.feuerrot.org
    memory: 4
    cpus: 4
    install: /debian-jessie/pxelinux.0
    interfaces:
      - switch: br-public
        mac: 00:16:3E:9F:F4:58
        address: 91.195.220.70
    storage:
      - pool: vg_ssd
        size: 120G
        dev: vda
  - name: guenter.luftamt-hersbruck.de
    memory: 1
    cpus: 1
    install: /archlinux/pxelinux.0
    interfaces:
      - switch: br-public
        mac: 00:16:3E:1C:56:44
        address: 91.195.220.71
    storage:
      - pool: vg_ssd
        size: 30G
        dev: vda
  - name: hermes.luftamt-hersbruck.de
    memory: 1
    cpus: 1
    install: /archlinux/pxelinux.0
    interfaces:
      - switch: br-public
        mac: 00:16:3E:64:1B:98
        address: 91.195.220.72
    storage:
      - pool: vg_ssd
        size: 20G
        dev: vda
  - name: bg1.luftamt-hersbruck.de
    memory: 1
    cpus: 1
    install: /archlinux/pxelinux.0
    interfaces:
      - switch: br-public
        mac: 00:16:3E:66:86:F1
        address: 91.195.220.73
    storage:
      - pool: vg_ssd
        size: 60G
        dev: vda
  - name: sternen.space
    memory: 4
    cpus: 1
    install: /archlinux/pxelinux.0
    interfaces:
      - switch: br-public
        mac: 00:16:3E:7E:FF:97
        address: 91.195.220.74
    storage:
      - pool: vg_ssd
        size: 80G
        dev: vda
  - name: bsd.reichsinter.net
    memory: 4
    cpus: 2
    install: /openbsd/pxeboot
    interfaces:
      - switch: br-public
        mac: 00:1C:14:B5:BF:24
        address: 91.195.220.75
    storage:
      - pool: vg_ssd
        size: 50G
        dev: vda
  - name: minecraft.zichy.de
    memory: 8
    cpus: 2
    install: /archlinux/pxelinux.0
    interfaces:
     - switch: br-public
       mac: 00:1C:14:B5:BD:24
       address: 91.195.220.76
    storage:
     - pool: vg_ssd
       size: 50G
       dev: vda
  - name: 600eur.the-space.agency
    memory: 4
    cpus: 2
    install: /openbsd/pxeboot
    interfaces:
      - switch: br-public
        mac: 00:16:3E:DA:B3:6C
        address: 91.195.220.78
    storage:
      - pool: vg_ssd
        size: 50G
        dev: vda
